from locators.login_locators import LoginLocators
from locators.cabinet_locators import CabinetLocators
from locators.catalogue_locators import CatalogueLocators
from locators.actions_locators import ActionsLocators
from locators.shop_list_locators import ShopListLocators
from locators.cart_locators import CartLocators
from locators.header_locators import HeaderLocators
from locators.footer_locators import FooterLocators
