class CatalogueLocators:

    LOWER_PRICE = '//div[@id="filter-price"]//input[@aria-label="from"]'
    HIGHER_PRICE = '//div[@id="filter-price"]//input[@aria-label="to"]'
    PRICE_RANGES = '//*[text()="Цена: от 500 до 1000 руб."]'
    INSTALLMENT_PAYMENT = '//div[@data-target="#filter-installment"]//div[@class="inp-box__view"]'
    INSTALLMENT_PAYMENT_SIGN = '//span[text()="Товары в рассрочку"]'
    DISCOUNT_GOODS = '//div[@data-target="#filter-markdown"]//div[@class="inp-box__view"]'
    DISCOUNT_GOODS_SIGN = '//span[text()="Товары с уценкой"]'
    ACTIONS_FILTER = '//div[@data-target="#filter-actions"]'
    HITS = '//*[@id="filter-actions"]/div/div[4]/div/label/div[1]'
    HITS_SIGN = '//span[text()="Акции: Лидеры продаж"]'
    XIAOMI_BRAND_CHECKBOX = '//*[@id="filter-692695"]/div/div[2]/div/label/div[1]'
    BRAND_SELECTED_SIGN = '//span[text()="Бренд: XIAOMI"]'
    SHOW_ALL_YEARS = '//*[@id="filter-726460"]/div/a/span[1]'
    YEAR_2023 = '//*[@id="filter-more-726460"]/div[2]/div/label/div[1]'
    YEAR_2023_SIGN = '//span[text()="Год выхода модели: 2023"]'
    SORT_DROPDOWN = '//div[2]/div/div/div[2]/div/button'
    VALUE_RATING = '//input[@value="rating"]'
    SORT_BY_RATING = '//span[text()="По рейтингу"]'
    CATALOGUE_CITY_LIST = '//span[@class="a-link city-link"]'
    CITY_OF_A_CLIENT_TO_SELECT = '//div[text()="Брест"]'
    FINAL_ACTUAL_CITY = '//span[text()="Бреста"]'
    ITEM_1 = '//button[@data-product_id="784765"]'
